"""Week 5 exploratory analysis. ALL DATA IS SYNTHETIC (OULAD file format, generated in conftest)."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from ml.analysis.eda import describe, markdown_table, run
from ml.training.config import TrainingConfig


def test_far_out_values_use_tukeys_outer_fences() -> None:
    values = pd.Series([*range(1, 11), 1000.0, np.nan])
    stats = describe(values)
    assert stats["n"] == 11
    assert stats["missing share"] == 1 / 12
    assert stats["far-out share"] == 1 / 11  # only 1000 lies beyond Q3 + 3*IQR


def test_markdown_table_formats_counts_decimals_and_missing() -> None:
    table = markdown_table(pd.DataFrame({"a": [3.0, 1234.5678], "b": [np.nan, 7]}))
    assert table.splitlines()[2] == "| 3 | — |"
    assert table.splitlines()[3] == "| 1,234.568 | 7 |"


def test_full_run_profiles_without_outcomes_or_identifiers(synthetic_dir: Path, tmp_path: Path) -> None:
    config = TrainingConfig.model_validate(
        {
            "run_name": "synthetic-eda",
            "dataset": {
                "name": "OULAD",
                "path": str(synthetic_dir),
                "provenance": "synthetic",
                "description": "Synthetic data in OULAD format generated by the test suite.",
            },
            "cutoff_days": [30, 60],
            "primary_cutoff_day": 60,
            "score_release_lag_days": 14,
            "split": {"train": ["2013B", "2013J"], "validation": ["2014B"], "test": ["2014J"]},
            "models": ["logistic_regression"],
            "imbalance_strategies": ["none"],
            "calibration_method": "sigmoid",
            "risk_level_quantiles": {"watch": 0.5, "elevated": 0.75, "high": 0.9},
            "top_fractions": [0.1],
            "selection_tolerance_pr_auc": 0.01,
            "stability_seeds": [0, 1],
            "bootstrap_iterations": 50,
            "random_seed": 1,
            "output_dir": str(tmp_path / "artifacts"),
            "report_dir": str(tmp_path / "reports"),
        }
    )
    out = run(config, tmp_path)
    report = (out / "report.md").read_text(encoding="utf-8")
    assert "Provenance: BENCHMARK" in report and "deliberately not shown" in report
    assert {p.name for p in (out / "figures").iterdir()} == {
        "clicks_per_registration.png",
        "assessment_scores.png",
        "submission_delay.png",
        "feature_correlation_day60.png",
        "feature_missingness.png",
    }
    for cutoff in (30, 60):
        features = pd.read_csv(out / "tables" / f"features_day{cutoff}.csv", index_col=0)
        assert "target" not in features.index and "target" not in features.columns  # no outcome association
    # synthetic student ids are 100000 and above, far from any count in these tables
    student_ids = set(pd.read_csv(synthetic_dir / "studentInfo.csv")["id_student"].astype(str))
    for table in (out / "tables").iterdir():
        frame = pd.read_csv(table)
        assert "id_student" not in frame.columns
        assert not student_ids & set(frame.astype(str).to_numpy().ravel())
