"""End-to-end: train on SYNTHETIC data, then exercise artifacts, SHAP and the inference API.

Numbers produced here are not model performance — the data is synthetic.
"""

from __future__ import annotations

import json
import math
import shutil
import uuid
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pytest

from ml.data.oulad import load_oulad
from ml.explainability.audiences import (
    FEATURE_TEXT,
    THEME_TEXT,
    explain,
    for_admin,
    for_mentor,
    for_student,
    student_theme,
)
from ml.explainability.shap_explainer import ModelExplainer
from ml.features.definitions import FEATURE_NAMES, FEATURE_VERSION
from ml.features.oulad_features import build_oulad_features
from ml.inference.service import InferenceService
from ml.models.artifact import ArtifactError, ModelArtifact
from ml.models.registry import ModelRegistry
from ml.models.registry_export import RegistryExportError, export_registry, registry_row
from ml.training.config import TrainingConfig
from ml.training.train import run

MODELS = ("logistic_regression", "random_forest", "xgboost")


@pytest.fixture(scope="module")
def trained(synthetic_dir: Path, tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    out = tmp_path_factory.mktemp("run")
    config = TrainingConfig.model_validate(
        {
            "run_name": "synthetic-test",
            "dataset": {
                "name": "OULAD",
                "path": str(synthetic_dir),
                "provenance": "synthetic",
                "description": "Synthetic data in OULAD format generated by the test suite.",
            },
            "targets": ["academic", "course_failure", "engagement"],
            "min_class_count_per_split": 15,
            "primary_target": "academic",
            "calibration_check": {"train": ["2013B"], "calibrate": ["2013J"], "evaluate": ["2014B"]},
            "cutoff_days": [60],
            "primary_cutoff_day": 60,
            "score_release_lag_days": 14,
            "split": {"train": ["2013B", "2013J"], "validation": ["2014B"], "test": ["2014J"]},
            "models": list(MODELS),
            "imbalance_strategies": ["none", "balanced"],
            "calibration_method": "sigmoid",
            "risk_level_quantiles": {"watch": 0.5, "elevated": 0.75, "high": 0.9},
            "top_fractions": [0.1, 0.2],
            "selection_tolerance_pr_auc": 0.01,
            "stability_seeds": [0, 1],
            "bootstrap_iterations": 50,
            "random_seed": 1,
            "output_dir": str(out / "artifacts"),
            "report_dir": str(out / "reports"),
        }
    )
    summary = run(config, out)
    test_rows = build_oulad_features(load_oulad(synthetic_dir), 60, score_release_lag_days=14)
    return {
        "summary": summary,
        "registry_root": out / "artifacts",
        "report_root": out / "reports",
        "rows": test_rows[test_rows["split_group"] == "2014J"].reset_index(drop=True),
    }


@pytest.fixture(scope="module")
def service(trained: dict[str, Any]) -> InferenceService:
    return InferenceService(ModelRegistry(trained["registry_root"]))


def _payload(trained: dict[str, Any], row: int = 0, **overrides: Any) -> dict[str, Any]:
    record = trained["rows"].iloc[row]
    features = {name: (None if pd.isna(record[name]) else float(record[name])) for name in FEATURE_NAMES}
    payload: dict[str, Any] = {
        "student_id": "syn-0001",
        "prediction_date": "2014-11-30",
        "features": features,
    }
    payload.update(overrides)
    return payload


def _error(service: InferenceService, payload: Any) -> dict[str, Any]:
    result = service.predict_safe(payload)
    assert result["ok"] is False
    error: dict[str, Any] = result["error"]
    return error


# ------------------------------------------------------------------ artifacts


def test_every_model_is_saved_with_preprocessing_and_lineage(trained: dict[str, Any]) -> None:
    cutoff = trained["summary"]["cutoffs"][0]
    for name in MODELS:
        version = cutoff["models"][name]["model_version"]
        artifact = ModelArtifact.load(trained["registry_root"] / version)
        meta = artifact.metadata
        assert meta.feature_names == FEATURE_NAMES
        assert meta.feature_version == FEATURE_VERSION
        assert meta.dataset_version.startswith("oulad-")
        assert meta.data_provenance == "synthetic"
        assert meta.training_timestamp.tzinfo is not None
        assert meta.risk_thresholds.watch < meta.risk_thresholds.elevated < meta.risk_thresholds.high
        assert {
            "validation",
            "test",
            "test_bootstrap_ci",
            "test_calibration_comparison",
            "stability",
            "subgroups_test",
            "drift_train_vs_test",
            "monitoring_snapshot_test",
        } <= set(meta.metrics)
        assert meta.target == "academic"
        assert meta.leakage_check["passed"] is True
        # calibration is recorded as applied only when the out-of-time check says it helps
        decision = meta.calibration_decision
        assert decision["check_split"]["evaluate"] == ["2014B"]
        improved = decision["brier_calibrated"] < decision["brier_raw"] and (
            decision["ece_calibrated"] < decision["ece_raw"]
        )
        assert decision["apply"] is improved
        assert (meta.calibration_method == "none") is (not improved)
        assert len(meta.model_sha256) == 64
        steps = list(artifact.pipeline.named_steps)
        assert steps[-1] == "model"
        if name != "xgboost":
            assert "impute" in steps  # preprocessing travels with the model
        if name == "logistic_regression":
            assert "scale" in steps and artifact.background_means is not None


def test_active_model_and_reports(trained: dict[str, Any]) -> None:
    registry = ModelRegistry(trained["registry_root"])
    assert registry.active_version() == trained["summary"]["active_model_version"]
    report_dir = trained["report_root"] / trained["summary"]["run_id"]
    report = (report_dir / "report.md").read_text(encoding="utf-8")
    assert "Data provenance: SYNTHETIC" in report
    assert "not** model performance" in report
    assert "accuracy" not in report.lower()
    metrics = json.loads((report_dir / "metrics.json").read_text(encoding="utf-8"))
    assert metrics["cutoffs"][0]["selection_rationale"]
    assert metrics["leakage_checks"]["60"]["passed"] is True
    assert "Temporal leakage guard" in report and "day 60 passed" in report
    assert "Calibration decision" in report and "Largest gaps between groups" in report


def test_every_target_is_trained_separately(trained: dict[str, Any]) -> None:
    cutoffs = trained["summary"]["cutoffs"]
    assert [(c["target"], c["skipped"]) for c in cutoffs] == [
        ("academic", False),
        ("course_failure", False),
        ("engagement", True),
    ]
    failure = cutoffs[1]
    assert "-fail-" in failure["selected_model_version"]
    artifact = ModelArtifact.load(trained["registry_root"] / failure["selected_model_version"])
    assert artifact.metadata.target == "course_failure"
    assert "horizon" in artifact.metadata.target_definition
    # the active (live-default) model is the primary target, never a secondary one
    assert "-acad-" in trained["summary"]["active_model_version"]


def test_target_without_enough_data_is_skipped_not_trained(trained: dict[str, Any]) -> None:
    engagement = trained["summary"]["cutoffs"][2]
    assert "insufficient data" in engagement["skip_reason"]
    assert "models" not in engagement
    assert not any("-eng-" in p.name for p in trained["registry_root"].iterdir())
    report_dir = trained["report_root"] / trained["summary"]["run_id"]
    assert "**Not trained**" in (report_dir / "report.md").read_text(encoding="utf-8")


def test_monitoring_outputs_contain_no_student_identifiers(trained: dict[str, Any]) -> None:
    m = trained["summary"]["cutoffs"][0]["models"]["logistic_regression"]
    text = json.dumps({"snapshot": m["monitoring_snapshot_test"], "drift": m["drift_train_vs_test"]})
    assert "student_id" not in text and "syn-" not in text
    assert m["monitoring_snapshot_test"]["n_predictions"] == len(trained["rows"])


def test_tampered_artifact_is_refused(trained: dict[str, Any], tmp_path: Path) -> None:
    version = trained["summary"]["active_model_version"]
    copy = tmp_path / version
    shutil.copytree(trained["registry_root"] / version, copy)
    with (copy / "model.joblib").open("ab") as handle:
        handle.write(b"tampered")
    with pytest.raises(ArtifactError):
        ModelArtifact.load(copy)


@pytest.mark.parametrize("name", MODELS)
def test_shap_contributions_are_additive(trained: dict[str, Any], name: str) -> None:
    version = trained["summary"]["cutoffs"][0]["models"][name]["model_version"]
    artifact = ModelArtifact.load(trained["registry_root"] / version)
    explainer = ModelExplainer.from_artifact(artifact)
    X = trained["rows"].loc[:, list(FEATURE_NAMES)].astype(float).head(25)
    contributions = explainer.contributions(X)
    assert contributions.shape == (len(X), len(FEATURE_NAMES))
    np.testing.assert_allclose(
        contributions.sum(axis=1) + explainer.expected_value, explainer.model_output(X), atol=1e-4
    )


# ------------------------------------------------------------------ inference


def test_valid_request_returns_contract(service: InferenceService, trained: dict[str, Any]) -> None:
    result = service.predict_safe(_payload(trained, top_k=3))
    assert result["ok"] is True
    data = result["data"]
    uuid.UUID(data["prediction_id"])
    assert data["model_version"] == trained["summary"]["active_model_version"]
    assert 0.0 <= data["risk_probability"] <= 1.0
    assert data["risk_level"] in {"stable", "watch", "elevated", "high"}
    assert data["data_provenance"] == "synthetic"
    assert data["api_version"] == "1.0.0"
    assert data["target"] == "academic"
    factors = data["top_factors"]
    assert 1 <= len(factors) <= 3
    assert [f["rank"] for f in factors] == list(range(1, len(factors) + 1))
    magnitudes = [abs(f["contribution"]) for f in factors]
    assert magnitudes == sorted(magnitudes, reverse=True)
    for f in factors:
        assert f["feature"] in FEATURE_NAMES
        assert f["direction"] == ("increases_risk" if f["contribution"] > 0 else "decreases_risk")
        assert set(f) == {"feature", "contribution", "direction", "rank", "feature_value"}


def test_risk_level_comes_from_stored_thresholds(service: InferenceService, trained: dict[str, Any]) -> None:
    data = service.predict(_payload(trained))
    artifact = ModelRegistry(trained["registry_root"]).load(data.model_version)
    assert data.risk_level == artifact.metadata.risk_thresholds.level(data.risk_probability)


def test_explicit_null_means_missing_and_is_accepted(
    service: InferenceService, trained: dict[str, Any]
) -> None:
    payload = _payload(trained)
    payload["features"]["mean_score_to_date"] = None
    assert service.predict_safe(payload)["ok"] is True


def test_each_model_version_can_be_requested(service: InferenceService, trained: dict[str, Any]) -> None:
    for name in MODELS:
        version = trained["summary"]["cutoffs"][0]["models"][name]["model_version"]
        assert service.predict(_payload(trained, model_version=version)).model_version == version


def test_missing_feature(service: InferenceService, trained: dict[str, Any]) -> None:
    payload = _payload(trained)
    del payload["features"]["clicks_last_7d"]
    err = _error(service, payload)
    assert err["code"] == "missing_features"
    assert err["details"]["features"] == ["clicks_last_7d"]


@pytest.mark.parametrize("bad_value", ["12", True, [1], {"v": 1}])
def test_wrong_type(service: InferenceService, trained: dict[str, Any], bad_value: Any) -> None:
    payload = _payload(trained)
    payload["features"]["clicks_to_date"] = bad_value
    err = _error(service, payload)
    assert err["code"] == "invalid_type"
    assert err["details"]["features"] == ["clicks_to_date"]


def test_unknown_feature(service: InferenceService, trained: dict[str, Any]) -> None:
    payload = _payload(trained)
    payload["features"]["gender"] = 1.0
    err = _error(service, payload)
    assert err["code"] == "unknown_features"
    assert err["details"]["features"] == ["gender"]


@pytest.mark.parametrize("bad_value", [math.nan, math.inf, -math.inf])
def test_nan_and_infinite_values(
    service: InferenceService, trained: dict[str, Any], bad_value: float
) -> None:
    payload = _payload(trained)
    payload["features"]["last_score"] = bad_value
    err = _error(service, payload)
    assert err["code"] == "non_finite_value"
    assert err["details"]["features"] == ["last_score"]


def test_empty_input(service: InferenceService, trained: dict[str, Any]) -> None:
    assert _error(service, _payload(trained, features={}))["code"] == "empty_input"


def test_model_unavailable(tmp_path: Path, trained: dict[str, Any]) -> None:
    empty = InferenceService(ModelRegistry(tmp_path / "no-models"))
    assert _error(empty, _payload(trained))["code"] == "model_unavailable"


def test_corrupt_model_is_unavailable(tmp_path: Path, trained: dict[str, Any]) -> None:
    version = trained["summary"]["active_model_version"]
    shutil.copytree(trained["registry_root"] / version, tmp_path / version)
    (tmp_path / version / "model.joblib").write_bytes(b"not a model")
    corrupt = InferenceService(ModelRegistry(tmp_path))
    err = _error(corrupt, _payload(trained, model_version=version))
    assert err["code"] == "model_unavailable"


@pytest.mark.parametrize("version", ["../../etc/passwd", "bad version", "", "x" * 65])
def test_invalid_model_version(service: InferenceService, trained: dict[str, Any], version: str) -> None:
    assert _error(service, _payload(trained, model_version=version))["code"] == "invalid_model_version"


def test_unknown_model_version(service: InferenceService, trained: dict[str, Any]) -> None:
    err = _error(service, _payload(trained, model_version="does-not-exist-v1"))
    assert err["code"] == "model_not_found"


def test_provenance_guard_refuses_non_institutional_models(trained: dict[str, Any]) -> None:
    guarded = InferenceService(ModelRegistry(trained["registry_root"]), allowed_provenance={"institutional"})
    assert _error(guarded, _payload(trained))["code"] == "model_not_permitted"


@pytest.mark.parametrize(
    "payload",
    [
        "not an object",
        None,
        {"prediction_date": "2014-11-30", "features": {"x": 1}},
        {"student_id": "a", "prediction_date": "not-a-date", "features": {"x": 1}},
        {"student_id": "a", "prediction_date": "2014-11-30", "features": {"x": 1}, "extra": 1},
        {"student_id": "a b", "prediction_date": "2014-11-30", "features": {"x": 1}},
        {"student_id": "a", "prediction_date": "2014-11-30", "features": {"x": 1}, "top_k": 0},
    ],
)
def test_invalid_request_shape(service: InferenceService, payload: Any) -> None:
    err = _error(service, payload)
    assert err["code"] == "invalid_request"
    dumped = json.dumps(err["details"])
    assert "not-a-date" not in dumped and '"a b"' not in dumped  # raw values are never echoed


# ------------------------------------------------------------------ V3 audiences / V4 registry export

STUDENT_FORBIDDEN = ("risk", "fail", "withdraw", "dropout", "drop out", "probability", "model", "%", "shap")


@pytest.mark.parametrize("row", [0, 1, 2, 3, 4, 5])
def test_student_explanation_is_non_stigmatising(
    service: InferenceService, trained: dict[str, Any], row: int
) -> None:
    response = service.predict(_payload(trained, row=row))
    metadata = ModelRegistry(trained["registry_root"]).load(response.model_version).metadata
    text = json.dumps(for_student(response, metadata).as_dict()).lower()
    assert not any(word in text for word in STUDENT_FORBIDDEN)
    assert not any(ch.isdigit() for ch in text)  # no values, scores or probabilities
    assert not any(f in text for f in FEATURE_NAMES)  # no model feature keys


def test_student_themes_come_only_from_factors_that_raised_the_estimate(
    service: InferenceService, trained: dict[str, Any]
) -> None:
    registry = ModelRegistry(trained["registry_root"])
    for row in range(len(trained["rows"])):
        response = service.predict(_payload(trained, row=row, top_k=10))
        explanation = for_student(response, registry.load(response.model_version).metadata)
        if response.risk_level == "stable":
            assert explanation.focus_areas == ()
            continue
        allowed = {
            THEME_TEXT[t][0]
            for f in response.top_factors
            if f.direction == "increases_risk" and (t := student_theme(f.feature)) is not None
        }
        titles = [a.title for a in explanation.focus_areas]
        assert set(titles) <= allowed and len(titles) == len(set(titles)) <= 3


def test_prior_history_is_never_a_student_theme() -> None:
    for feature in ("num_of_prev_attempts", "studied_credits", "registration_lead_days", "prior_term_gpa"):
        assert student_theme(feature) is None


def test_every_model_feature_has_explanation_text() -> None:
    from ml.features.definitions import FEATURE_SETS

    for specs in FEATURE_SETS.values():
        for spec in specs:
            assert spec.name in FEATURE_TEXT, spec.name


def test_mentor_and_admin_explanations(service: InferenceService, trained: dict[str, Any]) -> None:
    response = service.predict(_payload(trained, top_k=5))
    metadata = ModelRegistry(trained["registry_root"]).load(response.model_version).metadata
    mentor = for_mentor(response, metadata)
    assert [f.feature for f in mentor.factors] == [f.feature for f in response.top_factors]
    assert mentor.risk_probability == response.risk_probability
    assert any("not causes" in c for c in mentor.caveats)
    assert any("synthetic" in c for c in mentor.caveats)  # provenance warning
    admin = for_admin(response, metadata)
    assert admin.provenance_permits_live_use is False
    assert admin.model_version == response.model_version
    assert "student_id" not in json.dumps(admin.as_dict())
    assert admin.calibration_reason == metadata.calibration_decision["reason"]


def test_explanations_refuse_mismatched_metadata(service: InferenceService, trained: dict[str, Any]) -> None:
    response = service.predict(_payload(trained))
    other = trained["summary"]["cutoffs"][1]["selected_model_version"]
    metadata = ModelRegistry(trained["registry_root"]).load(other).metadata
    with pytest.raises(ValueError, match="different model versions"):
        explain("student", response, metadata)


def test_registry_export_rows_match_the_database_contract(trained: dict[str, Any]) -> None:
    rows = export_registry(trained["registry_root"])
    assert len(rows) == 6  # 2 trained targets x 3 models; skipped targets produce no artifacts
    for row in rows:
        assert row["status"] == "development"
        assert row["institution_id"] is None
        assert row["target"] in {"academic", "course_failure"}
        assert len(row["artifact_sha256"]) == 64
        assert row["validation_metrics"]["validation"]["pr_auc"] is not None
        assert "decision" in row["calibration_metrics"]
        assert "student_id" not in json.dumps(row)


def test_registry_export_scoping_rules(trained: dict[str, Any]) -> None:
    version = trained["summary"]["active_model_version"]
    metadata = ModelRegistry(trained["registry_root"]).load(version).metadata
    with pytest.raises(RegistryExportError, match="only institutional"):
        registry_row(metadata, institution_id=uuid.uuid4())
    institutional = metadata.model_copy(update={"data_provenance": "institutional"})
    with pytest.raises(RegistryExportError, match="must name the institution"):
        registry_row(institutional)
    assert registry_row(institutional, institution_id=uuid.UUID(int=1))["institution_id"] == str(
        uuid.UUID(int=1)
    )
